global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "engine"
    static_configs:
      - targets: ["engine:8080"]
    metrics_path: /metrics

  - job_name: "fetch"
    static_configs:
      - targets: ["fetch:8081"]
    metrics_path: /metrics

  - job_name: "geo"
    static_configs:
      - targets: ["geo:8082"]
    metrics_path: /metrics
